### ISSUE TITLE
Unable to generate serenity-reports 

### ISSUE THREAD

**Issue by u-sandeep** [serenity-bdd/serenity-junit-starter#33]
I see the below stack trace on standard output

java.lang.NoSuchMethodError: 'java.lang.Class org.junit.platform.engine.support.descriptor.MethodSource.getJavaClass()'
	at net.serenitybdd.junit5.SerenityTestExecutionListener.testingThisTest(SerenityTestExecutionListener.java:425) ~[serenity-junit5-3.1.15.jar:na]
	at net.serenitybdd.junit5.SerenityTestExecutionListener.testStarted(SerenityTestExecutionListener.java:396) ~[serenity-junit5-3.1.15.jar:na]
	at net.serenitybdd.junit5.SerenityTestExecutionListener.executionStarted(SerenityTestExecutionListener.java:236) ~[serenity-junit5-3.1.15.jar:na]
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.lambda$executionStarted$6(TestExecutionListenerRegistry.java:99) ~[junit-platform-launcher-1.6.3.jar:1.6.3]
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.lambda$notifyEach$1(TestExecutionListenerRegistry.java:67) ~[junit-platform-launcher-1.6.3.jar:1.6.3]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) ~[na:na]

java.lang.NoSuchMethodError: 'java.lang.reflect.Method org.junit.platform.engine.support.descriptor.MethodSource.getJavaMethod()'
	at net.serenitybdd.junit5.SerenityTestExecutionListener.updateResultsUsingTestAnnotations(SerenityTestExecutionListener.java:356) ~[serenity-junit5-3.1.15.jar:na]
	at net.serenitybdd.junit5.SerenityTestExecutionListener.testFinished(SerenityTestExecutionListener.java:334) ~[serenity-junit5-3.1.15.jar:na]
	at net.serenitybdd.junit5.SerenityTestExecutionListener.executionFinished(SerenityTestExecutionListener.java:277) ~[serenity-junit5-3.1.15.jar:na]
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.lambda$executionFinished$10(TestExecutionListenerRegistry.java:109) ~[junit-platform-launcher-1.6.3.jar:1.6.3]
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.lambda$notifyEach$1(TestExecutionListenerRegistry.java:67) ~[junit-platform-launcher-1.6.3.jar:1.6.3]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) ~[na:na]

**Comment by u-sandeep** [comment]
Dependencies used:

testImplementation 'net.serenity-bdd:serenity-core:3.1.15'
    testImplementation "net.serenity-bdd:serenity-junit5:3.1.15"
    testImplementation "org.junit.jupiter:junit-jupiter-api:5.9.0"
    testImplementation "org.junit.jupiter:junit-jupiter-engine:5.9.0"
    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.9.0'
    testImplementation 'org.junit.vintage:junit-vintage-engine:5.9.0'
    testImplementation 'net.serenity-bdd:serenity-rest-assured:3.1.15'
    testImplementation 'net.serenity-bdd:serenity-spring:3.1.15'

**Comment by u-sandeep** [comment]
<img width="1792" alt="Screenshot 2022-11-01 at 9 36 23 AM" src="https://user-images.githubusercontent.com/38466006/199156711-31427afb-12ed-4feb-b98a-6533754d4de8.png">

This screenshot is from serenity-junit-starter project report

**Comment by u-sandeep** [comment]
<img width="1792" alt="Screenshot 2022-11-01 at 9 37 14 AM" src="https://user-images.githubusercontent.com/38466006/199156818-c3e0f006-4712-4825-945b-fb8d3d35ad84.png">
This is from my project. I added spring integration also to the project by using @SpringBootTest annotation and running with
@ExtendsWith(SerenityJunit5Extension.class)

Previously, we were using serenity, junit4 & springboot and running tests with @RunWith(SpringIntegrationSerenityRunner)...This works fine and reports are generated.
